### ISSUE TITLE
Build fails on Ubuntu 22

### ISSUE THREAD

**Issue by 1Guardian** [Kron4ek/wine-wayland#1]
Hello, I wanted to build wine-wayland to do some testing, but the build fails with: 

/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libwayland-client.so when searching for -lwayland-client
/usr/bin/ld: cannot find -lwayland-client: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libwayland-client.so when searching for -lwayland-client
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libwayland-cursor.so when searching for -lwayland-cursor
/usr/bin/ld: cannot find -lwayland-cursor: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libwayland-cursor.so when searching for -lwayland-cursor

both libwayland-client0:i386 and libwayland-cursor0:i386 are installed, but it makes no difference. Is this tied to an inability to build it on 64bit systems even with multiarch, or is there a dev package actually missing?

Thanks!

**Comment by Kron4ek** [comment]
Hello,

> or is there a dev package actually missing?

Probably. Make sure you have `libwayland-dev:i386` installed.

**Comment by 1Guardian** [comment]
yep that was it. Thanks!
