### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by ghost** [Kron4ek/wine-wayland#2]
[wine-13](https://gitlab.collabora.com/alf/wine/-/tags) is already here, but there have been no updates since May. Is this project abandoned?

**Comment by Kron4ek** [comment]
I don't know, i am not the author of the Wine-Wayland project, i just update the source code whenever new version is available [here](https://github.com/varmd/wine-wayland).

**Comment by ghost** [comment]
Sorry, I created the issue in the wrong repository
